---
- name: Backup
  hosts: dellos6
  gather_facts: false
  vars:
    backup_dir: "/home/semaphore/backups/6"
  tasks:
    - name: Backup
      dellemc.os6.os6_config:
        backup: true
        backup_options:
          dir_path: "{{ backup_dir }}"
