---
- name: Gather security rules
  hosts: PA
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output
      ansible.builtin.debug:
        msg: "{{ sec_rules }}"
