---
- name: Export Palo configuration and save to a file
  hosts: PA
  connection: local  # Force local connection, skipping SSH
  gather_facts: false  # Skip gathering facts, which requires SSH
  vars:
    base_path: "/opt/semaphore/backups/PA"
  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        current_month: "{{ lookup('pipe', 'date +%B') }}"
        current_day: "{{ lookup('pipe', 'date +%d') }}"
      delegate_to: localhost

    - name: Create month folder if it doesn't exist
      file:
        path: "{{ base_path }}/{{ current_month }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Create day folder inside month folder
      file:
        path: "{{ base_path }}/{{ current_month }}/{{ current_day }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      

    - name: Set the curl command as a variable
      set_fact:
        current_curl: "https://{{ inventory_hostname }}/api/?type=export&category=configuration&key={{ lookup('env', 'API_KEY' + inventory_hostname | upper) }}"

    - name: Run curl to export configuration and save to a file
      command: curl -k "{{ current_curl }}" -o "{{ base_path }}/{{ current_month }}/{{ current_day }}/{{ inventory_hostname }}_palo_config.xml"
      register: curl_result

    - name: Check if the file was created
      stat:
        path: "{{ base_path }}/{{ current_month }}/{{ current_day }}/{{ inventory_hostname }}_palo_config.xml"
      register: file_status

    - name: Show success message
      debug:
        msg: "Palo configuration has been saved to '{{ base_path }}/{{ current_month }}/{{ current_day }}/{{ inventory_hostname }}_palo_config.xml'"
      when: file_status.stat.exists
      when: file_status.stat.exists
