- name: Export Palo configuration and save to a file
  hosts: localhost
  tasks:
    - name: Ensure /opt/semaphore directory exists
      file:
        path: /opt/semaphore
        state: directory
        mode: '0755'

    - name: Run curl to export configuration and save to a file
      command: curl -k "https://10.15.9.10/api/?type=export&category=configuration&key={{ lookup('env', 'API_KEY') }}" -o /opt/semaphore/palo_config.xml
      register: curl_result

    - name: Check if the file was created
      stat:
        path: /opt/semaphore/palo_config.xml
      register: file_status

    - name: Show success message
      debug:
        msg: "Palo configuration has been saved to /opt/semaphore/palo_config.xml"
      when: file_status.stat.exists
